### ISSUE TITLE
logger needs to be polyfilled

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/trailpack-sails#1]
In Sails, `sails.log(message)` will use the default loglevel. In winston, the statement fails.

**Comment by jaumard** [comment]
Here is the log when I try to do `this.app.log("test")` or `this.app.log("info", "test")` from a trailpack (here repl)

```
TypeError: this.app.log is not a function
    at REPL.configure (/Users/jaumard/IdeaProjects/trailpack-repl/index.js:17:18)
    at /Users/jaumard/Downloads/trails-example-app-master/node_modules/trails/index.js:60:26
    at process._tickDomainCallback (node.js:400:9)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:118:18)
    at node.js:952:3
```

**Comment by tjwebb** [comment]
I've decided to solve this a different way which obsoletes this issue.
